language: python
python:
  - "3.4"
  - "3.5"
# command to run tests
install:
  - pip install -r requirements.txt
script:
  - python lr_for_the_masses/rr_mlm/test_mlm.py
  - python lr_for_the_masses/rr_mlm/test_rr.py
  - python unittest_lr.py
  - python unittest_mlm.py
  - python unittest_mlr.py